### ISSUE TITLE
No module named "gi"

### ISSUE THREAD

**Issue by James46113** [lyrebird-voice-changer/lyrebird#73] opened 2021-04-23 22:35 UTC
I'm using Linux mint cinnamon, and just tried to install lyrebird with the .deb package. But when I tried to run the app, it came up with a python error: 
Traceback (most recent call last):
  File "/usr/share/lyrebird/app.py", line 2, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
When I try to install gi, it says it is already installed. This is probably a problem with my laptop, but any help would be appreciated.
Thanks

**Comment by Sorry-Im-Stupid** [comment] 2021-05-28 20:06
I'm having this exact problem.
To expand on this, I do have python3.7 installed, but:
```
python -V
Python 2.7.12
```

I have like 30 tabs open, trying to figure out why _all of this process_.
Essentially I think the problem is Mint is running on 2.7 by default, and it won't switch to 3.7 automatically, so there must be a way to tell lyrebird to use 3.7, but I have **no idea** how.
I've tried to do the alt-install/alt-update thing, to no avail.

**Comment by harrego** [comment] 2022-05-07 14:08
I haven't seen this issue pop up in a while so I'm assuming it's been fixed by the distros.

**Closed by harrego** 2022-05-07 14:08 UTC
